name = "notionapikey"
compatibility_date = "2023-11-21"
account_id = "your_account_id"
workers_dev = true
main = "worker.js"

# Permettre l'importation du module @notionhq/client
[build]
command = "npm install"

# Optionnel : configurer des variables d'environnement si nécessaire
[vars]
# NOTION_API_BASE_URL = "https://api.notion.com"